# Generates AirtimeSolo.py — the whole radio as ONE file for the iPhone.
#
# Embeds airtime.html inside the script (base64, so no quoting or escaping can
# break it) and serves it from memory. Nothing is read from disk and nothing is
# downloaded, so the phone needs no companion file and no Mac.
#
# Run this after editing airtime.html to regenerate the single-file version.

import base64
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SOURCE = os.path.join(HERE, "airtime.html")
TARGET = os.path.join(HERE, "AirtimeSolo.py")

TEMPLATE = '''# AirtimeSolo.py — the whole radio, in one file, running on this iPhone.
#
# Generated by build_solo.py; edit airtime.html and regenerate rather than
# editing the blob below. Copy this single file anywhere on the phone and run
# it: no companion files, no Mac, no home Wi-Fi.

import base64
import functools
import http.server
import socketserver
import sys
import threading

PORT = 8642
URL = "http://127.0.0.1:{{}}/".format(PORT)

PAGE = base64.b64decode("{blob}")


class Handler(http.server.BaseHTTPRequestHandler):
    """Serves the embedded page for every path, straight from memory."""

    def do_GET(self):
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(PAGE)))
        self.end_headers()
        self.wfile.write(PAGE)

    def log_message(self, *args):
        pass  # keep the Pythonista console clean


def start_server():
    socketserver.TCPServer.allow_reuse_address = True
    httpd = socketserver.TCPServer(("127.0.0.1", PORT), Handler)
    threading.Thread(target=httpd.serve_forever, daemon=True).start()
    return httpd


def run_in_pythonista(httpd):
    """Keep the page in Pythonista's own web view.

    Handing off to Safari backgrounds this script, and iOS suspends background
    processes — which kills the server the page is loading from.
    """
    import ui

    view = ui.WebView(name="Airtime")
    view.load_url(URL)
    view.present("fullscreen", hide_title_bar=False)
    view.wait_modal()          # blocks here while you listen
    httpd.shutdown()


def run_anywhere(httpd):
    """Fallback for a-Shell/Pyto/desktop: open a browser, hold the server up."""
    import time
    import webbrowser

    webbrowser.open(URL)
    print("Serving {{}} — leave this running while you listen.".format(URL))
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        httpd.shutdown()


if __name__ == "__main__":
    server = start_server()
    try:
        run_in_pythonista(server)
    except ImportError:
        run_anywhere(server)
'''

if __name__ == "__main__":
    with open(SOURCE, "rb") as fh:
        blob = base64.b64encode(fh.read()).decode("ascii")
    with open(TARGET, "w") as fh:
        fh.write(TEMPLATE.format(blob=blob))
    print("wrote {} ({:,} bytes)".format(TARGET, os.path.getsize(TARGET)))
